config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create, :edit] do
    member do
      get :followings
      get :followers
    end
    collection do
      get :search
    end
  end

  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :likes
    end
  end

  resources :wants
  resources :prefecture
  resources :relationships, only: [:create, :destroy]
  resources :favorites

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :want
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  has_many :wants
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :wants
  has_many :favorites
  has_many :fav_wants, through: :favorites, source: :want


  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def like(want)
    favorites.find_or_create_by(want_id: want.id)
   end

   def unlike(want)
    favorite = favorites.find_by(want_id: want.id)
    favorite.destroy if favorite
   end

   def liked?(other_user)
    self.fav_wants.include?(other_user)
  end
end

app/models/want.rb
class Want < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :prefecture
  has_many :favorites, dependent: :destroy

  validates :content, presence: true, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

  def counts(user)
    @count_wants = user.wants.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
    @count_likes = user.fav_wants.count
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in

  def index
    
  end

  def show

  end

  def create
    want = Want.find(params[:want_id])
    current_user.like(want)
    flash[:success] = 'お気に入りに追加しました。'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    want = Want.find(params[:want_id])
    current_user.unlike(want)
    flash[:success] = 'お気に入りを解除しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in

  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザをフォローしました。'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'ユーザのフォローを解除しました。'
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url

  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers, :likes]
  
  def index
    @pagy, @users = pagy(User.order(id: :desc), items: 25)
  end

  def show
    @user = User.find(params[:id])
    @want = current_user.wants.build
    @pagy, @wants = pagy(current_user.wants.order(id: :desc))
    counts(@user)
    @pagy, @favorites = pagy(@user.fav_wants.order(id: :desc))
    counts(@user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = '名前 は正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = '名前 は更新されませんでした'
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def followings
    @user = User.find(params[:id])
    @pagy, @followings = pagy(@user.followings)
    counts(@user)
  end

  def followers
    @user = User.find(params[:id])
    @pagy, @followers = pagy(@user.followers)
    counts(@user)
  end

  def likes
    @user = User.find(params[:id])
    @pagy, @favorites = pagy(@user.fav_wants)
    counts(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def index
    @want = current_user.wants.build  # form_with 用
    @pagy, @wants = pagy(current_user.wants.order(id: :desc))
    @pagy, @users = pagy(User.order(id: :desc), items: 25)
  end

  def show
    @user = User.find(params[:id])
    @want = current_user.wants.build
    @pagy, @wants = pagy(current_user.wants.order(id: :desc), item: 25)
    @prefecture = current_user.prefecture.build
    @pagy, @prefectures = pagy(current_user.prefectures.order(id: :desc), item: 25)
  end

  def new
  end

  def create
    @want = current_user.wants.build(want_params)
    if @want.save
      flash[:success] = 'メッセージを投稿しました。'
      redirect_to user_path
    else
      @pagy, @wants = pagy(current_user.wants.order(id: :desc))
      flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      redirect_to root_url
    end
    end
  end

  def destroy
    @want.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: user_path)
  end

  private

  def want_params
    params.require(:want).permit(:content,:image)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost
      redirect_to root_url
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/helpers/wants_helper.rb
module WantsHelper

end

app/views/favorites/_favorite_button.html.erb
<% if current_user.liked?(want) %>
  <%= form_with(model: current_user.favorites.find_by(want_id: want.id), local: true, method: :delete) do |f| %>
    <%= hidden_field_tag :want_id, want.id %>
    <%= f.submit 'Unfavorite', class: 'btn btn-danger btn-sm' %>
  <% end %>
<% else %>
  <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
    <%= hidden_field_tag :want_id, want.id %>
    <%= f.submit 'Favorite', class: 'btn btn-primary btn-sm' %>
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), method: :delete) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger w-100' %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary w-100' %>
    <% end %>
  <% end %>
<% end %>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/users/edit.html.erb
<div class="main mt-5 mb-5">
  <div class="card devise-card">
    <div class="form-wrap">
      <div class="form-group text-center">
        <h2 class="logo-img mx-auto"></h2>
        <p class="text-secondary h3 mb-3">ユーザーの編集ページ</p>
      </div>
      <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group mt-2 mx-5">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, autofocus: true, placeholder: "フルネーム", class: "form-control" %>
      </div>
      </div>
        <div class="actions mx-5 mt-4 mb-5">
          <%= f.submit "登録する", class: "btn btn-primary w-100" %>
        </div>
        <div class="btn">
        <%= link_to '一覧に戻る', users_path %>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/users/followers.html.erb
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm" id="header1">
    <img src="assets/logo.png" alt="">
    <p class="h5 my-0 me-md-auto fw-normal">Let's know about Japan</p>

    <div class="jumbotron"> 
    <nav class="my-2 my-md-0 me-md-3">
      <a class="p-2 text-dark" href="#"><%= link_to 'ホーム', root_path %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'みんなのとうこう', wants_path %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'プロフィール', user_path(current_user) %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'ログアウト', logout_path, method: :delete %></a>
    </nav>
  </div>
  </header>

<section id="section6">
    <h1 class="text-center">みんなのとうこう</h1>

<div class="row mt-5">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid rounded-circle" src="<%= gravatar_url(@user, { size: 300 }) %>" alt="">
      </div>
      <ul id="section1ul2" class="mx-3">
            <li><%= @count_followings %></li>
            <li><a href="<%= followings_user_path(@user) %>">Folloing</a></li>
            <li><%= @count_followers %></li>
            <li><a href="<%= followers_user_path(@user) %>">Follwers</a></li>
             <li><%= @count_likes %></li>
            <li><a href="<%= likes_user_path(@user) %>">Favorite</a></li>
          </ul>
          <a class="mx-5" href="" id="section1a1">Followerのとうこう</a>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge bg-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge bg-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%# <%= render 'users', users: @followers %> 
  </div>
</div>
</section>

<div class="container">
  <a class="btn btn-primary" href="" id="a3">Facebook</a>
</div>

<footer>
  <div id="footer-left">
    <ul id="footerul">
     <li><a href="">ホーム</a></li>
     <li><a href="">みんなのとうこう</a></li>
     <li><a href="">プロフィール</a></li>
     <li><a href="">ログアウト</a></li>
    </ul>
  </div>

  <div id="footer-right">
     <img src="assets/logo.png" alt="">
  </div>
</footer>

app/views/users/followings.html.erb
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm" id="header1">
    <img src="assets/logo.png" alt="">
    <p class="h5 my-0 me-md-auto fw-normal">Let's know about Japan</p>

    <div class="jumbotron"> 
    <nav class="my-2 my-md-0 me-md-3">
      <a class="p-2 text-dark" href="#"><%= link_to 'ホーム', root_path %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'みんなのとうこう', wants_path %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'プロフィール', user_path(current_user) %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'ログアウト', logout_path, method: :delete %></a>
    </nav>
  </div>
  </header>

  <section id="section6">
    <h1 class="text-center">みんなのとうこう</h1>

<div class="row mt-5">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid rounded-circle" id="bg-icon" src="<%= gravatar_url(@user, { size: 300 }) %>" alt="">
      </div>
      <ul id="section1ul2" class="mx-3">
            <li><%= @count_followings %></li>
            <li><a href="<%= followings_user_path(@user) %>">Folloing</a></li>
            <li><%= @count_followers %></li>
            <li><a href="<%= followers_user_path(@user) %>">Follwers</a></li>
          </ul>
          <a class="mx-5" href="" id="section1a1">Followerのとうこう</a>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge bg-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge bg-secondary"><%= @count_followers %></span></a></li>
    </ul>

    <%# #↓フォロー表示 %>
      <%# <%= render 'users', users: @followings %>  
  </div>
</div>
</section>


<div class="container">
  <a class="btn btn-primary" href="" id="a3">Facebook</a>
</div>

<footer>
  <div id="footer-left">
    <ul id="footerul">
     <li><a href="">ホーム</a></li>
     <li><a href="">みんなのとうこう</a></li>
     <li><a href="">プロフィール</a></li>
     <li><a href="">ログアウト</a></li>
    </ul>
  </div>

  <div id="footer-right">
     <img src="assets/logo.png" alt="">
  </div>
</footer>

app/views/users/likes.html.erb
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm" id="header4">
    <img src="assets/logo.png" alt="">
    <p class="h5 my-0 me-md-auto fw-normal">Let's know about Japan</p>

    <div class="jumbotron"> 
    <nav class="my-2 my-md-0 me-md-3">
      <a class="p-2 text-dark" href="#"><%= link_to 'ホーム', root_path %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'みんなのとうこう', wants_path %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'プロフィール', user_path(current_user) %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'ログアウト', logout_path, method: :delete %></a>
    </nav>
  </div>
  </header>

  <section id="section6">
    <h1 class="text-center">みんなのとうこう</h1>

<div class="row mt-5">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid rounded-circle" id="bg-icon" src="<%= gravatar_url(@user, { size: 300 }) %>" alt="">
      </div>
      <ul id="section1ul2" class="mx-3">
            <li><%= @count_followings %></li>
            <li><a href="<%= followings_user_path(@user) %>">Folloing</a></li>
            <li><%= @count_followers %></li>
            <li><a href="<%= followers_user_path(@user) %>">Follwers</a></li>
            <li><%= @count_likes %></li>
            <li><a href="<%= likes_user_path(@user) %>">Favorite</a></li>
          </ul>
          <a class="mx-5" href="" id="section1a1">Followerのとうこう</a>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
        <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Favorite  <span class="badge bg-secondary"><%= @count_likes %></span></a></li>
    </ul>
    </ul>

    <%# #↓ %>
      <%# <%= render 'wants/wants', wants: @favorites %>  
  </div>
</div>
</section>


<div class="container">
  <a class="btn btn-primary" href="" id="a3">Facebook</a>
</div>

<footer>
  <div id="footer-left">
    <ul id="footerul">
     <li><a href="">ホーム</a></li>
     <li><a href="">みんなのとうこう</a></li>
     <li><a href="">プロフィール</a></li>
     <li><a href="">ログアウト</a></li>
    </ul>
  </div>

  <div id="footer-right">
     <img src="assets/logo.png" alt="">
  </div>
</footer>

app/views/users/show.html.erb
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm" id="header1">
    <img src="assets/logo.png" alt="">
    <p class="h5 my-0 me-md-auto fw-normal">Let's know about Japan</p>

    <div class="jumbotron"> 
    <nav class="my-2 my-md-0 me-md-3">
      <a class="p-2 text-dark" href="#"><%= link_to 'ホーム', root_path %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'みんなのとうこう', wants_path %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'プロフィール', user_path(current_user) %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'ログアウト', logout_path, method: :delete %></a>
    </nav>
  </div>
  </header>

  <section id="section6">
    <h1 class="text-center" id="section1h1">プロフィール</h1>

     <div class="container d-flex align-items-center" id="profile1">
        <div id="profile-left">
          <img class="rounded me-2 rounded-circle" src="<%= gravatar_url(@user, { size: 200 }) %>" alt="">
           <ul id="section1ul1">
             <li><%= @user.name %></li>
             <li><%= link_to '編集', edit_user_path(@user) %></li>
           </ul>
          <%# <p id="section1p1">こんにちは。<br>TAKAです。大学生です。</p>  %>
          <ul id="section1ul2" class="ml-1">
            <li><%= @count_followings %></li>
            <li><a href="<%= followings_user_path(@user) %>">Folloing</a></li>
            <li><%= @count_followers %></li>
            <li><a href="<%= followers_user_path(@user) %>">Follwers</a></li>
            <li><%= @count_likes %></li>
            <li><a href="<%= likes_user_path(@user) %>">Favorite</a></li>
          </ul>  
          <a href="" id="section1a1">Followerのとうこう</a>
        </div>
    
        <div id="profile-right">
         <% if @wants.any? %>
          <% @wants.each do |want| %>
          <% @prefectures.each do |prefecture| %>
            <div id="profile-right-right">
              <ul id="profile-right-rightul1">
                <li id="profile-right-rightli1"><%= prefecture.name %></li>
                <% if current_user == want.user %>
                <li><%= link_to "削除", want, method: :delete, data: { confirm: "You sure?" } %></li>
                <% end %>
              </ul>
              <%= prefecture.image %>
            </div>

            <div id="profile-right-left">
              <p><%= want.content %></p>
              </div>
               <% end %>
               <% end %>
          </div>
           <%== pagy_bootstrap_nav(@pagy) %>
           <% end %>
        </div>
     </div>
</section>


  <button id="btn3" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">ついかする</button>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
<%= form_with(model: @want, local: true) do |f| %>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">いきたいところ・したいこと</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <form enctype="multipart/form-data" action="/areas" accept-charset="UTF-8" data-remote="true" method="post"><input type="hidden" name="authenticity_token" value="w1N3p1TrssWZRYiW+iVSZm2nFS/r/9xccMCM5ZFYrbpFhuyvptkOlrdHaHh/YxogTqWG0ra4K/zgO8FULd61kw==" />
            <div class="validate-area"></div>
            <div class="form-group">
              <%= f.label :area_country_id, '都道府県' %>
              <%= f.select :area_country_id, {'北海道': 337, '東京': 231, '愛知': 850, '大阪': 1, '京都': 886, '福岡': 670, '長崎': 240}, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
            </div>
      
          <div class="mb-3">
            <label for="message-text" class="col-form-label">したい事:</label>
             <%= f.text_area :content, class: 'form-control', rows: 3 %>
          </div>
          <div class="field">
            <%= f.file_field :image %>
            <%= f.submit 'アップロードする'%>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">とじる</button>
        <%= f.submit 'ついかする', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="container">
  <a class="btn btn-primary" href="" id="a3">Facebook</a>
</div>

<footer>
  <div id="footer-left">
    <ul id="footerul">
     <li><a href="">ホーム</a></li>
     <li><a href="">みんなのとうこう</a></li>
     <li><a href="">プロフィール</a></li>
     <li><a href="">ログアウト</a></li>
    </ul>
  </div>

  <div id="footer-right">
     <img src="assets/logo.png" alt="">
  </div>
</footer>

app/views/wants/index.html.erb
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm" id="header5">
    <img src="assets/logo.png" alt="">
    <p class="h5 my-0 me-md-auto fw-normal">Let's know about Japan</p>

    <div class="jumbotron"> 
    <nav class="my-2 my-md-0 me-md-3">
      <a class="p-2 text-dark" href="#"><%= link_to 'ホーム', root_path %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'みんなのとうこう', wants_path %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'プロフィール', user_path(current_user) %></a>
      <a class="p-2 text-dark" href="#"><%= link_to 'ログアウト', logout_path, method: :delete %></a>
    </nav>
  </div>
  </header>

<div id="section5" class="container">
   <h1 class="text-center">みんなのとうこう</h1>

   <div class="container mt-5 mx-5 card"> 
<% if @wants.any? %>
  <ul class="list-unstyled">
    <% @wants.each do |want| %>
      <li class="mb-3 d-flex">
        <img class="rounded me-2" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <p><%= link_to 'View profile', user_path(user), class: "text-decoration-none" %></p>
        <div>
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= @prefecture.name %></p>
            <p><%= @want.content %></p>
          </div>
        </div>
         <li><a href=""><%= render 'favorites/favorite_button', micropost: micropost %></a></li>
         <li><%= @count_likes %></li>
      </li>
    <% end %>
  </ul>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>
</div>
</div> 



<div class="container">
  <a class="btn btn-primary" href="" id="a3">Facebook</a>
</div>

<footer>
  <div id="footer-left">
    <ul id="footerul">
     <li><a class="p-2 text-dark" href="#"><%= link_to 'ホーム', root_path %></a></li>
     <li><a class="p-2 text-dark" href="#"><%= link_to 'みんなのとうこう', wants_path %></a></li>
     <li><a class="p-2 text-dark" href="#"><%= link_to 'プロフィール', user_path(current_user) %></a></li>
     <li><a class="p-2 text-dark" href="#"><%= link_to 'ログアウト', logout_path, method: :delete %></a></li>
    </ul>
  </div>

  <div id="footer-right">
     <img src="assets/logo.png" alt="">
  </div>

</footer>

app/views/wants/new.html.erb
<h1>Wants#new</h1>
<p>Find me in app/views/wants/new.html.erb</p>